# -*- coding: utf-8 -*-
"""biblioteca_exercicio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jHa8eIohK21f_SH7z2zpk-e1d57sxION
"""

#Aquecimento

#Escreva um código para instalar a versão 3.7.1 da biblioteca matplotlib.

!pip install matplotlib==3.7.1

#Escreva um código para importar a biblioteca numpy com o alias np.

import numpy as np

#Crie um programa que leia a seguinte lista de números e escolha um número desta aleatoriamente.
lista = [8, 12, 54, 23, 43, 1, 90, 87, 105, 77]
from random import randrange

randrange(100)

#Crie um programa que sorteia, aleatoriamente, um número inteiro positivo menor que 100.
#Dica: use a função randrange() da biblioteca random. Essa função recebe como parâmetro o valor limite
#para a escolha aleatória ou um intervalo se passado o limite mínimo e máximo. Por exemplo, randrange(5) gera valores inteiros menores que 5.

from random import randrange

randrange(100)

#Crie um programa que solicite à pessoa usuária digitar dois números inteiros e calcular a potência do 1º número elevado ao 2º.

#Dica: use a função pow() da biblioteca math

from math import pow

base = int(input("Digite a base da potência: "))
expoente = int(input("Digite o expoente da potência: "))
print(f"{base} elevado a {expoente} é igual a {pow(base, expoente)}")