# -*- coding: utf-8 -*-
"""Biblioteca.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e7Qy3o0msUnlFk7yMY8vdmpk4-f2sClF
"""

!pip install matplotlib

import matplotlib.pyplot as plt

from random import randrange, sample

lista = []

for i in range(0, 20):
  lista.append(randrange(100))

sample(lista, 5)

#Usando import nome_biblioteca
import math

n = int(input("Digite um número positivo para calcular sua raiz quadrada:"))
print(f"\nA raiz quadrada de {n} é igual a {math.sqrt(n)}")

#Usando from nome_biblioteca import *
from math import *

n = int(input("Digite um número positivo para calcular sua raiz quadrada:"))
print(f"\nA raiz quadrada de {n} é igual a {sqrt(n)}")