# -*- coding: utf-8 -*-
"""biblioteca_exercicio_aplicando_projeto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E0CVdOeC-jt4cAaDvZMCKFJ0cxJTP-O7
"""

#Aplicando a projetos
#Um programa deve ser escrito para sortear uma pessoa seguidora de uma rede social para ganhar um prêmio.
#A lista de participantes é numerada e devemos escolher aleatoriamente um número de acordo com a quantidade de participantes.
#Peça à pessoa usuária para fornecer o número de participantes do sorteio e devolva para ela o número sorteado.

from random import randint
# Transformando a quantidade de participantes de string para inteiro
n = int(input("Digite o nº de participantes do sorteio: "))
# Sorteando um número no intervalo de 1 até a quantidade de participantes
print(f"O número sorteado foi {randint(1, n)}")

#Você recebeu uma demanda para gerar números de token para acessar o aplicativo de uma empresa.
#O token precisa ser par e variar de 1000 até 9998. Escreva um código que solicita à pessoa usuária
#o seu nome e exibe uma mensagem junto a esse token gerado aleatoriamente.

"Olá, [nome], o seu token de acesso é [token]! Seja bem-vindo(a)!"
from random import randrange

nome = input("Qual o seu nome? ")
# Gerando um token par de 1000 a 9998. O randrange tem o intervalo aberto em 10000, ou seja,
# não considera 10000 como opção de escolha (token >= 1000 e token < 10000)
token = randrange(1000, 10000, 2)

print(f"Olá, {nome}, o seu token de acesso é {token}! Seja bem-vindo(a)!")

# Para diversificar e atrair novos(as) clientes, uma lanchonete criou um item misterioso em seu cardápio chamado "salada de frutas surpresa".
#Neste item, são escolhidas aleatoriamente 3 frutas de uma lista de 12 para compor a salada de frutas da pessoa cliente.
#Crie o código que faça essa seleção aleatória de acordo com a lista abaixo:

frutas = ["maçã", "banana", "uva", "pêra",
          "manga", "coco", "melancia", "mamão",
          "laranja", "abacaxi", "kiwi", "ameixa"]
          from random import choices

# Lista das frutas disponíveis
frutas = ["maçã", "banana", "uva", "pêra","manga", "coco",
          "melancia", "mamão", "laranja", "abacaxi", "kiwi", "ameixa"]

# Gerando uma lista com a escolha aleatoria de 3 frutas
salada = choices(frutas, k=3)

# Imprimindo os itens da lista de frutas gerada
print(f"A salada surpresa é: {salada[0]}, {salada[1]} e {salada[2]}")