# -*- coding: utf-8 -*-
"""calculadora _com _operadores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X3EUGIsj3UQa1tL8zK3K1x9095lG7qnB
"""

#Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a soma dos dois valores.
a = int(input('Digite o primeiro valor: '))
b = int(input('Digite o segundo valor: '))
print(a+b)

#2.	Crie um programa que solicite três valores numéricos à pessoa usuária e imprima a soma dos três valores.
a = int(input('Digite o primeiro valor: '))
b = int(input('Digite o segundo valor: '))
c = int(input('Digite o terceiro valor: '))
print(a+b+c)

#	Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a subtração do primeiro pelo o segundo valor.
a = int(input('Digite o primeiro valor: '))
b = int(input('Digite o segundo valor: '))
print(a-b)

#4.	Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a multiplicação dos dois valores.
a = int(input('Digite o primeiro valor: '))
b = int(input('Digite o segundo valor: '))
print(a*b)

#5.	Crie um programa que solicite dois valores numéricos, um numerador e um denominador, e realize a divisão entre os dois valores. Deixe claro que o valor do denominador não pode ser 0.
numerador = int(input('Digite o numerador: '))
denominador = int(input('Digite o denominador (OBS: o valor não pode ser nulo): '))
print(numerador/denominador)

#6.	Crie um programa que solicite dois valores numéricos, um operador e uma potência, e realize a exponenciação entre esses dois valores.
operador = int(input('Digite o operador valor: '))
potencia = int(input('Digite a potência valor: '))
print(operador**potencia)

#7.	Crie um programa que solicite dois valores numéricos, um numerador e um denominador e realize a divisão inteira entre os dois valores. Deixe claro que o valor do denominador não pode ser 0.
numerador = int(input('Digite o numerador: '))
denominador = int(input('Digite o denominador (OBS: o valor não pode ser nulo): '))
print(numerador//denominador)

#8.	Crie um programa que solicite dois valores numéricos, um numerador e um denominador, e retorne o resto da divisão entre os dois valores. Deixe claro que o valor do denominador não pode ser 0.
numerador = int(input('Digite o numerador: '))
denominador = int(input('Digite o denominador (OBS: o valor não pode ser nulo): '))
print(numerador%denominador)

#9.	Crie um código que solicita 3 notas de um estudante e imprima a média das notas.

nota_1 = float(input('Digite a 1° nota: '))
nota_2 = float(input('Digite a 2° nota: '))
nota_3 = float(input('Digite a 3° nota: '))
print(f'Média {(nota_1+nota_2+nota_3)/3}.')

#10.	Crie um código que calcule e imprima a média ponderada dos números 5, 12, 20 e 15 com pesos respectivamente iguais a 1, 2, 3 e 4.
media_ponderada = (5*1 + 12*2 + 20*3 + 15*4) / (1+2+3+4)
print(f'Média {media_ponderada}.')