# -*- coding: utf-8 -*-
"""condicionais.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ewI2RGuV94WFxbtXEvbui4siUcuzsBx2
"""

#IF condição:
#	faça algo

#Maior que (>)
idade_maria = int(input('Digite a idade da Maria: '))
idade_beatriz = int(input('Digite a idade da Beatriz: '))

if idade_maria > idade_beatriz:
  print('Maria é mais velha que Beatriz.')

#Menor que (<)

idade_maria = int(input('Digite a idade da Maria: '))
idade_beatriz = int(input('Digite a idade da Beatriz: '))

if idade_maria < idade_beatriz:
  print('Maria é mais nova que Beatriz.')

#Maior ou igual a (>=)
empregados_empresa_1 = int(input('Digite a quantidade de empregados da empresa 1: '))
empregados_empresa_2 = int(input('Digite a quantidade de empregados da empresa 2: '))

if empregados_empresa_1 >= empregados_empresa_2:
  print('Empresa 1 tem uma quantidade de empregados maior ou igual à empresa 2.')

#Menor ou igual a (<=)
empregados_empresa_1 = int(input('Digite a quantidade de empregados da empresa 1: '))
empregados_empresa_2 = int(input('Digite a quantidade de empregados da empresa 2: '))

if empregados_empresa_1 <= empregados_empresa_2:
  print('Empresa 1 tem uma quantidade de empregados menor ou igual à empresa 2.')

#Igual a (==)
livro_1 = input('Digite o título do 1° livro: ')
livro_2 = input('Digite o título do 2° livro: ')

if livro_1 == livro_2:
  print('Os livros têm o mesmo título')

#Diferente de (!=)
livro_1 = input('Digite o título do 1° livro: ')
livro_2 = input('Digite o título do 2° livro: ')

if livro_1 != livro_2:
  print('Os livros têm títulos diferentes')

