# -*- coding: utf-8 -*-
"""editando_textos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1503DuUsy_U8USStF5A2Zc4HfwYACiH0M
"""

#1.	Crie uma variável chamada “frase” e atribua a ela uma string de sua escolha. Em seguida, imprima a frase na tela.
frase = 'Olá Python!'
print(frase)

2.	Crie um código que solicite uma frase e depois imprima a frase na tela

frase = input('Digite uma frase: ')
print(frase)

#3.	Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase digitada mas com todas as letras maiúsculas.
frase = input('Digite uma frase: ')
print(frase.upper())

#4.	Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase digitada mas com todas as letras minúsculas.
frase = input('Digite uma frase: ')
print(frase.lower())

#5.	Crie uma variável chamada “frase” e atribua a ela uma string de sua escolha. Em seguida, imprima a frase sem espaços em branco no início e no fim.
frase = ' Olá Python!  '
print(frase.strip())

#6.	Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase sem espaços em branco no início e no fim.
frase = input('Digite uma frase: ')
print(frase.strip())

#7.	Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase sem espaços em branco no início e no fim e em letras minúsculas.
frase = input('Digite uma frase: ')
print(frase.strip().lower())

8.	Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as vogais “e” trocadas pela letra “f”.
frase = input('Digite uma frase: ')
print(frase.lower().replace('e','f'))

9.	Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as vogais “a” trocadas pela caractere “@”.

frase = input('Digite uma frase: ')
print(frase.lower().replace('a',chr(64)))

10.	Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as consoantes “s” trocadas pelo caractere “$”.
frase = input('Digite uma frase: ')
print(frase.lower().replace('s',chr(36)))