# -*- coding: utf-8 -*-
"""escopo_varivael.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sOHyLwxhkJ_riy2KNFzVtZB8ovN_uqrH
"""

#Para saber mais: escopo de uma variável

x = 7

def soma():
  y = 9
  print(x + y)
  soma()