# -*- coding: utf-8 -*-
"""Exercicio_condicionais.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16b8tqdFFjRLTHkJW2dQYHo0HRfU6wEM7
"""

#1) Escreva um programa que peça à pessoa usuária para fornecer dois números e exibir o número maior
# Coletar os números
num1 = float(input('Digite o 1° número: '))
num2 = float(input('Digite o 2° número: '))

# Comparamos ambos os números e descobrimos qual é o maior
if num1 > num2:
    print(f'O primeiro número é maior: {num1}')
elif num2 > num1:
    print(f'O segundo número é maior: {num2}')
else: # Caso os números sejam iguais
    print('Os dois números são iguais.')

#2) Escreva um programa que solicite o percentual de crescimento de produção de uma empresa e informe se houve um crescimento (porcentagem positiva) ou decrescimento (porcentagem negativa).
# Coleta do percentual
variacao = float(input('Digite o percentual de crescimento: '))

# Verifica se o valor é positivo ou negativo com uma verificação se o número
# é maior ou menor que 0
if variacao > 0:
    print(f'Houve um crescimento de {variacao}%')
elif variacao < 0:
    print(f'Houve um decrescimento de {variacao}%')
else:
    print('Não houve crescimento ou decrescimento.')

#3) Escreva um programa que determine se uma letra fornecida pela pessoa usuária é uma vogal ou consoante.
# Coletamos a letra da pessoa usuária como minúscula
letra = input('Digite uma letra: ').lower()
vogais = 'aeiou' # string contendo todos os dados

# Verificamos se a letra está nas vogais com in
if letra in vogais:
    print('A letra é uma vogal.')
else:
    print('A letra é uma consoante.')

#4) Escreva um programa que leia valores médios de preços de um modelo de carro por 3 anos consecutivos e exiba o valor mais alto e mais baixo entre esses três anos.
# Coletamos os preços dos 3 anos
preco_ano1 = float(input('Informe o preço médio do carro no primeiro ano: '))
preco_ano2 = float(input('Informe o preço médio do carro no segundo ano: '))
preco_ano3 = float(input('Informe o preço médio do carro no terceiro ano: '))

# Determinamos o maior valor através de comparações
maior = preco_ano1
if preco_ano2 > maior:
  maior = preco_ano2
if preco_ano3 > maior:
  maior = preco_ano3

# Determinamos o menor valor através de comparações
menor = preco_ano1
if preco_ano2 < menor:
  menor = preco_ano2
if preco_ano3 < menor:
  menor = preco_ano3

# Mostramos o resultado
print(f'O preço mais alto foi de R$ {maior}.')
print(f'O preço mais baixo foi de R$ {menor}.')

#5) Escreva um programa que pergunte sobre o preço de três produtos e indique qual é o produto mais barato para comprar.
# Coletamos os preços dos três produtos
p1 = float(input('Digite o preço do primeiro produto: '))
p2 = float(input('Digite o preço do segundo produto: '))
p3 = float(input('Digite o preço do terceiro produto: '))

# Verificamos qual produto é o mais barato usando o operador lógico 'and'
if p1 < p2 and p1 < p3:
    print('O primeiro produto é o mais barato.')
elif p2 < p1 and p2 < p3:
    print('O segundo produto é o mais barato.')
elif p3 < p1 and p3 < p2:
    print('O terceiro produto é o mais barato.')
elif p1 == p2 == p3:
    print('Os produtos possuem o mesmo preço.')
else:
    # Identificamos quais produtos possuem o mesmo preço, se for o caso
    if p1 == p2:
        print('O primeiro e o segundo produtos são os mais baratos.')
    elif p2 == p3:
        print('O segundo e terceiro produtos são os mais baratos.')
    elif p1 == p3:
        print('O primeiro e o terceiro produtos são os mais baratos.')

#6) Escreva um programa que leia três números e os exiba em ordem decrescente.
# Coletamos os 3 números
num1 = int(input('Informe o primeiro número: '))
num2 = int(input('Informe o segundo número: '))
num3 = int(input('Informe o terceiro número: '))

# Comparação entre os 3 números
if (num1 >= num2) and (num1 >= num3):
    print(num1)
    if num2 >= num3:
        print(num2)
        print(num3)
    else:
        print(num3)
        print(num2)
elif (num2 >= num1) and (num2 >= num3):
    print(num2)
    if num1 >= num3:
        print(num1)
        print(num3)
    else:
        print(num3)
        print(num1)
else:
    print(num3)
    if num1 >= num2:
        print(num1)
        print(num2)
    else:
        print(num2)
        print(num1)

#7) Escreva um programa que pergunte em qual turno a pessoa usuária estuda ("manhã", "tarde" ou "noite") e exiba a mensagem "Bom Dia!", "Boa Tarde!", "Boa Noite!", ou "Valor Inválido!", conforme o caso.
# Coletamos o turno de estudo
turno = input('Digite em qual turno você estuda (manhã, tarde ou noite): ')

# Comparamos a entrada com todas as opções e imprimimos o resultado.
if turno == 'manhã':
  print('Bom Dia!')
elif turno == 'tarde':
  print('Boa Tarde!')
elif turno == 'noite':
  print('Boa Noite!')
else:
  print('Valor Inválido!')

#8) Escreva um programa que peça um número inteiro à pessoa usuária e determine se ele é par ou ímpar. Dica: Você pode utilizar o operador módulo %.
# Coletamos os dados
num = int(input('Digite um número: '))

# Verificamos se o número é par através do resultado do módulo
if num % 2 == 0:
    print('O número é par.')
else:
    print('O número é ímpar.')

#9) Escreva um programa que peça um número à pessoa usuária e informe se ele é inteiro ou decimal.
# Coletamos os dados
num = float(input('Digite um número: '))

# Verificamos se o número é inteiro ou decimal através do resultado do módulo
if num % 1 == 0:
    print('O número é inteiro.')
else:
    print('O número é decimal.')

#10) Um programa deve ser escrito para ler dois números e, em seguida, perguntar à pessoa usuária qual operação ele deseja realizar. O resultado da operação deve incluir informações sobre o número - se é par ou ímpar, positivo ou negativo e inteiro ou decimal.
# Coletamos os números a serem operados e solicitamos a operação desejada pela pessoa usuária
num1 = float(input('Informe o primeiro número: '))
num2 = float(input('Informe o segundo número: '))
operacao = input('Informe a operação desejada (+, -, *, /): ')

# Verificamos o operador que foi selecionado e executa a operação matemática conforme a seleção
if operacao == '+':
    resultado = num1 + num2
elif operacao == '-':
    resultado = num1 - num2
elif operacao == '*':
    resultado = num1 * num2
elif operacao == '/':
    resultado = num1 / num2
else: # Especificamos um resultado caso a pessoa usuária não digite alguma das operações corretamente.
    print('Operação inválida, resultado da operação será 0')
    resultado = 0

#  Fazemos as mesmas verificações das questões anteriores para fazer o relatório do cálculo entre números
if resultado % 1 == 0:
    print('O resultado é inteiro.')
else:
    print('O resultado é decimal.')

if resultado > 0:
    print('O resultado é positivo.')
elif resultado == 0:
    print('O resultado é neutro.')
else:
    print('O resultado é negativo.')

if resultado % 2 == 0:
    print('O resultado é par.')
else:
    print('O resultado é ímpar.')