# -*- coding: utf-8 -*-
"""exercicios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iQ3b4jivmWhOZ4caQpGLGVHs7AGE5BR4
"""

#Crie um programa que solicite à pessoa usuária digitar seu nome, e imprima “Olá, [nome]!”.

nome = input('Digite seu nome: ')
print(f'Olá, {nome}.')

#Crie um programa que solicite à pessoa usuária digitar seu nome e idade, e imprima “Olá, [nome], você tem [idade] anos.”
nome = input('Digite seu nome: ')
idade = int(input('Digite sua idade: '))
print(f'Olá {nome}, você tem {idade} anos.')

#Crie um programa que solicite à pessoa usuária digitar seu nome, idade e altura em metros, e imprima “Olá, [nome], você tem [idade] anos e mede [altura] metros!”
nome = input('Digite seu nome: ')
idade = int(input('Digite sua idade: '))
altura = float(input('Digite sua altura: '))
print(f'Olá {nome}, você tem {idade} anos e mede {altura} metros!')

