# -*- coding: utf-8 -*-
"""Expressoes_logicas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/178IzDIgZQQ7gpcKPYkQ1NQTee1IMXrpw
"""

#and
t1 = t2 = True
f1 = f2 = False
if t1 and t2:
  print('expressão verdadeira')
else:
  print('expressão falsa')

#or
if f1 or f2:
  print('expressão verdadeira')
else:
  print('expressão falsa')

#Operador lógico: not
if not t1:
  print('expressão verdadeira')
else:
  print('expressão falsa')

#Operador: in