# -*- coding: utf-8 -*-
"""funcoes_retorno.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eARIvij8Rv1EV3-MWWDAlCuVKtA80r2X
"""

#Funções com retorno
#def <nome>(<param_1>, <param_2>, ..., >param_n>):
#   <instruções>
#    return resultado

# Notas do(a) estudante
notas = [8.5, 9.0, 6.0, 10.0]

def media(lista):
    calculo = sum(lista) / len(lista)
    return calculo

resultado = media(notas)