# -*- coding: utf-8 -*-
"""funcao_sem_parametro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_X1VpQgBS_jSbXczkeLPKQ1EuTKzjsMb
"""

#def é a palavra-chave para criar uma função.
#def <nome>():
#    <instruções>

def media():
    calculo = (10 + 9 + 8) / 3
    print(calculo)

media ()