# -*- coding: utf-8 -*-
"""funcao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14HnhP8w6jECvljEq4hMEK330oQoQ7nez
"""

# funções embutidas  - Built-in function
#print(), type() ou list()
#SUM - SOMA
#Após feita a soma, precisamos pegar o tamanho da lista,
#já que precisamos fazer a divisão pela quantidade de valores existente. Para isso, usamos a função len() em uma variável qtd_notas.
#Porém, para entender o funcionamento de round() ou de qualquer outro método, podemos utilizar a função help() de duas maneiras:


#As built-in functions são funções integradas ao Python, ou seja,
#já estão disponíveis no interpretador sem necessidade de importação. Uma de suas vantagens é a eficiência.

#Situação 1: A escola em que estamos construindo o nosso case de dados compartilhou os dados
#das notas de um estudante para que pudéssemos calcular a média deste em até uma casa decimal.
#Os dados recebidos correspondem a um dicionário com as chaves
#indicando o trimestre em questão e os valores das notas de cada trimestre do estudante em uma dada matéria.

#Notas do(a) estudante
notas = {'19 Trimestre': 8.5, '2° Trimestre': 9.5, '3º trimestre': 7}
notas

# Calculando a soma
soma = 0

for nota in notas.values():
    soma += nota

soma

# Usando a função embutida sum()
somatorio = sum(notas.values())

somatorio

# Usando a função embutida len()
qtd_notas = len(notas)

qtd_notas

# Calculando a média
media = somatorio / qtd_notas

media

help(round)

media = somatorio / qtd_notas
media = round(media,1)
media