# -*- coding: utf-8 -*-
"""funcoes_retorno2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VSAeSy1LGnbJCM4RRhuIfh9TwlUbC7l_
"""

#Recebemos uma nova demanda, desta vez, de calcular a média de um estudante a partir de
#uma lista e retornar tanto a média quanto a situação do estudante ("Aprovado(a)"
#se a nota for maior ou igual a 6.0, caso contrário, será "Reprovado(a)").
#Além disso, precisamos exibir um pequeno texto em que indicamos a média do(a) estudante e
#qual a situação. Os dados recebidos correspondem a uma lista contendo apenas as notas de um estudante em uma dada matéria.

# Notas do(a) estudante
notas = [6.0, 7.0, 9.0, 5.0]

def boletim(lista):
    media = sum(lista) / len(lista)

    if media >= 6:
        situacao = "Aprovado(a)"
    else:
        situacao = "Reprovado(a)"

    return (media, situacao)

boletim(notas)

media, situacao = boletim(notas)

media

situacao

print(f'O(a) estudante atingiu uma média de {media} e foi {situacao}.')