# -*- coding: utf-8 -*-
"""funcao_com_parametro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jLknQeNZK1VCABkWrIMy6qCc1iOKWi0l
"""

#def <nome>(<param_1>, <param_2>, ..., >param_n>):
#    <instruções>

def media(nota_1, nota_2, nota_3):
    calculo = (nota_1 + nota_2 + nota_3)/3
    print(calculo)

media(3, 6, 9)

nota1 = 8
nota2 = 7
nota3 = 6

media(nota1, nota2, nota3)