# -*- coding: utf-8 -*-
"""funcoes_Lambda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c0bCGgG-rqoWHYrdCUf10ui1nn037_WT
"""

#Funções Lambda

#Uma função lambda, também chamada de função anônima,
#não precisa ser definida, ou seja, não possui um nome. Além disso, pode ser descrita uma única linha.

#lambda <variavel>: <expressao>

#Nesta nova demanda, precisamos criar uma calculadora simples da média ponderada de notas de uma dada matéria.
#Vamos requisitar ao usuário a entrada das 3 notas (N1, N2, N3) do estudante e devolver a média ponderada deste estudante.
#Os pesos das notas são de, respectivamente 3, 2, 5. Precisamos exibir um pequeno texto em que indicamos a média do(a) estudante.
#Vamos resolver esse desafio?

# Comparando uma função de qualitativo no formato de função para função anônima
nota = float(input("Digite a nota do(a) estudante: "))

def qualitativo(x):
    return x + 0.5

qualitativo(nota)

# Testando a mesma função para uma função lambda
nota = float(input("Digite a nota do(a) estudante: "))

qualitativo = lambda x: x + 0.5

qualitativo(nota)

# Recebendo as notas e calculando a média ponderável
N1 = float(input("Digite a 1ª nota do(a) estudante: "))
N2 = float(input("Digite a 2ª nota do(a) estudante: "))
N3 = float(input("Digite a 3ª nota do(a) estudante: "))

media_ponderavel = lambda x, y, z: (x * 3 + y * 2 + z * 5)/10

# Exibindo a média
print(f'O(a) estudante atingiu uma média de {media_estudante}')

map(<lambda function>, <iterador>)