# -*- coding: utf-8 -*-
"""laco_momento_dos_projetos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pz1ZN4XUgbKnkjqTFcGUU7o_859HgcmE
"""

#Escreva um programa que gere a tabuada de um número inteiro de 1 a 10, de acordo com a escolha da pessoa usuária.
#Como exemplo, para o número 2, a tabuada deve ser mostrada no seguinte formato:

#Tabuada do 2:
#2 x 1 = 2
#2 x 2 = 4
#[...]
#2 x 10 = 20

# Pedir o número
num = int(input('Informe um número inteiro de 1 a 10: '))

# Vamos gerar a tabuada
print(f'Tabuada do {num}:')
for i in range(1, 11):
    resultado = num * i
    print(f'{num} x {i} = {resultado}')

#Os números primos possuem várias aplicações dentro da Ciência de Dados em criptografia e segurança, por exemplo. Um número primo é aquele que é
#divisível apenas por um e por ele mesmo. Assim, faça um programa que
#peça um número inteiro e determine se ele é ou não um número primo.

# Solicitamos o número
num = int(input("Digite o número: "))

# Assumimos que o número é primo até que se prove o contrário
eh_primo = True

# Números abaixo de 2 não são primos
if num <= 1 :
  eh_primo = False
else:
    for i in range(2, num):
        # Se o número for divisível por qualquer número dentro deste intervalo,
        # ele não é primo, portanto, mudamos a variável 'eh_primo' para False e saímos do loop.
        if num % i == 0:
            eh_primo = False
            break

# Verifica se 'eh_primo' ainda é True, o que significa que o número passou pelo loop
# sem ser divisível por nenhum número além de 1 e ele mesmo.
if eh_primo:
    # Se for o caso, o número é primo.
    print(f'O número {num} é primo')
else:
    # Caso contrário, o número não é primo.
    print(f'O número {num} não é primo')

#Vamos entender a distribuição de idades de pensionistas de uma empresa de previdência.
#Escreva um programa que leia as idades de uma quantidade não informada de clientes e mostre a distribuição em intervalos de [0-25], [26-50], [51-75] e [76-100].
#Encerre a entrada de dados com um número negativo.

# Coletamos as idades dos clientes
idade = int(input('Informe a idade (ou um número negativo para encerrar): '))

# Inicializamos as variáveis de contadores
contador_0_25 = 0 # contador de idades entre 0 e 25
contador_26_50 = 0 # contador de idades entre 26 e 50
contador_51_75 = 0 # contador de idades entre 51 e 75
contador_76_100 = 0 # contador de idades entre 76 e 100

# nosso código executa sempre até o valor de idade for negativa
while idade >= 0:
    # contamos cada caso
    if idade >= 0 and idade <= 25:
        contador_0_25 += 1
    elif idade >= 26 and idade <= 50:
        contador_26_50 += 1
    elif idade >= 51 and idade <= 75:
        contador_51_75 += 1
    elif idade >= 76 and idade <= 100:
        contador_76_100 += 1

    # Repetir o processo de entrada de dados até que seja digitado um número negativo
    idade = int(input('Informe a idade (ou um número negativo para encerrar): '))

# Mostramos os resultados
print('Distribuição de idades:')
print('[0-25]:', contador_0_25)
print('[26-50]:', contador_26_50)
print('[51-75]:', contador_51_75)
print('[76-100]:', contador_76_100)

# Inicializamos as variáveis contadoras
votos_candidato1 = 0
votos_candidato2 = 0
votos_candidato3 = 0
votos_candidato4 = 0
votos_nulos = 0
votos_branco = 0

# Início do laço para ler os votos
for i in range(0,20):
    voto = int(input('Informe seu voto: '))
    if voto == 1:
        votos_candidato1 += 1
    elif voto == 2:
        votos_candidato2 += 1
    elif voto == 3:
        votos_candidato3 += 1
    elif voto == 4:
        votos_candidato4 += 1
    elif voto == 5:
        votos_nulos += 1
    elif voto == 6:
        votos_branco += 1
    else:
        print("Voto inválido.")

print(f'Votos candidato 1: {votos_candidato1}')
print(f'Votos candidato 2: {votos_candidato2}')
print(f'Votos candidato 3: {votos_candidato3}')
print(f'Votos candidato 4: {votos_candidato4}')
print(f'Votos nulos: {votos_nulos}')
print(f'Votos em branco: {votos_branco}')
print(f'Percentual de votos nulos: {(votos_nulos / 20 * 100)}')
print(f'Percentual de votos em branco: {(votos_branco / 20 * 100)}')