# -*- coding: utf-8 -*-
"""laco_for

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1htXXJJDVP2wFXkl6oD_4OdHhCnhzzqJS
"""

# laço FOR
#for elemento in conjunto:
	#código a ser executado para cada elemento
for contador in range(1,11):
	print(contador)