# -*- coding: utf-8 -*-
"""laco_exercicio_while.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eCY5hjEeMMM5aYLIPVmBtp-IlBI_UOze
"""

# coletar e imprimir a média de duas notas de 3 estudantes

contador = 1
while contador <= 3:
    nota_1 = float(input("Digite a primeira nota: "))
    nota_2 = float(input("Digite a segunda nota: "))

    print(f"A média das notas é: {(nota_1 + nota_2) / 2}")
    contador += 1