# -*- coding: utf-8 -*-
"""lista_tuplas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Xix_ZxtJ8e5sY2Fmk5I70UMnqLt2WO8
"""

# As TUPLAS são estruturas de dados usadas para armazenar itens em uma única variável.
#São imutáveis, ou seja, não permitem adição, alteração ou remoção de seus elementos. Após ser construída, seus dados são fixos.

estudantes = ["João", "Maria", "José", "Cláudia", "Ana"]
estudantes

#LISTA

##uma lista de tuplas
from random import randint

def gera_codigo():
  return str(randint(0,999))#vamos gerar um código/função, def gera_codigo() e
  #usamos o built-in function do str(), para transformar a escolha aleatória no nosso estudante.

codigo_estudantes = []

for i in range(len(estudantes)):
  codigo_estudantes.append((estudantes[i], estudantes[i][0] + gera_codigo()))

codigo_estudantes