# -*- coding: utf-8 -*-
"""lista.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1STGIWKGZs0QKsxT1phqzSVP5NUHU1Wa-
"""

#Uma lista é uma coleção ordenada de elementos que podem ser ou não do mesmo tipo.
#Podemos ter strings, números, tuplas e até mesmo listas.
#[[a1, a2,...,an], [b1, b2,...,bn], ..., [n1, n2,...,nn]]

#Recebemos a demanda de transformar uma lista com o nome e as notas dos três trimestres de estudantes em uma
# lista simples com os nomes separados das notas e uma lista de listas com as três notas de cada estudante separadas umas das outras.

#Os dados recebidos correspondem a uma lista com os nomes e as respectivas notas de cada estudante.
# Vamos resolver esse desafio? Para facilitar o nosso entendimento do processo vamos trabalhar com uma turma fictícia de 5 estudantes.

notas_turma = ['João', 8.0, 9.0, 10.0, 'Maria', 9.0, 7.0, 6.0, 'José', 3.4, 7.0, 7.0, 'Cláudia', 5.5, 6.6, 8.0, 'Ana', 6.0, 10.0, 9.5]
#Nome dos estudante e notas

nomes = []
notas_juntas = []

for i in range(len(notas_turma)): # len é o comprimento
  if i % 4 ==0:
      nomes.append(notas_turma[i])
  else:
      notas_juntas.append(notas_turma[i])

nomes

notas_juntas