# -*- coding: utf-8 -*-
"""manipulacao_listas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DZQ0YqZCuvD501gcTaoaSQi3qnZSOFio
"""

#Manipulação de Lista LEN()
lista = ['Mara Cunha',9.5,10,8.0, True]
len(lista)