# -*- coding: utf-8 -*-
"""Type_hint.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VB0YkswtW5E9hz01ztOTqKabbQA7EzMm
"""

#def <nome>(<param>: <tipo_param>) -> <tipo_retorno>:
#  <instruções>
#  return resultado

# a nossa função recebe uma lista do tipo list e retorna uma variável do tipo float
def media(lista: list) -> float:
  calculo = sum(lista) / len(lista)
  return calculo

media