# -*- coding: utf-8 -*-
"""variavel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12URnYiofegFCjiuAnWR01d6sPQCWwGXb
"""

idade = 5

print(idade)

idade = 10
print(idade)

idade = 15
idade

nome = 'texto'
nome

i =  5
type(i)

f =  9.0
type(f)

s = 'texto'
type(s)

b = True
type(b)

nome_aluno = 'Fabricio Daniel'
idade_aluno = 13
media_aluno = 8.60
situacao_aprovado = True
print(nome_aluno, idade_aluno, media_aluno, situacao_aprovado)

quant_seguranca = 5
sal_seguranca = 3000

quant_docente = 16
sal_docente = 6000

quant_diretoria = 1
sal_diretoria = 12500

# como somar

total_empregados = quant_seguranca + quant_docente + quant_diretoria
print(total_empregados)

#como subtrair
diferenca_salarios = sal_diretoria - sal_seguranca
diferenca_salarios

media = (quant_seguranca * sal_seguranca + quant_docente * sal_docente + quant_diretoria * sal_diretoria) / (total_empregados)
print(media)  # Imprima o valor de 'media'

2*3

operador = 2
potencia = 3
operador ** potencia

7%3

dividendo = 7
divisor = 3
dividendo % divisor

7 // 3

numerador = 7
denominador = 3
numerador // denominador

# strings
s1 = 'Alura'
s2 = " Alura"
print(type(s1), type(s2))

texto = 'Nome da  professora: '
 texto

# Converte uma string para Maiúscula
texto.upper()

#Coverte  uma stinrg para Minúsculas str.lower
texto.lower()

#Metódo substitui de todas as ocorrências do texto'antigo' na string por 'novo
texto.replace('n', 'N')

texto = texto.strip().replace('nome da ', 'Nome da ').upper()
texto

chr(64)

chr(79) + chr(108) + chr(225)

#Coletando Dados (INPUT)  é um valor textual
nome = input('Escreva seu nome: ')

nome

ano_entrada = input('Escreva o ano de ingresso da(o) estudante: ')

ano_entrada = int(input('Escreva o ano de ingresso da(o) estudante: '))

type(ano_entrada)

nota_entrada = float(input('Digite a nota do teste de ingresso: '))
print (f'Ano de entrada: { ano_entrada} -  nota do teste: { nota_entrada}')

nome = "Ana Maria"
idade = 17
print(f"O nome da aluna é {nome} e sua idade é {idade} anos.")

nome_aluno = 'Fabricio Daniel'

print('Nome do aluno: %s' %(nome_aluno))

nome_aluno = 'Fabricio Daniel'
idade_aluno = 15
media_aluno = 8.45

print('Nome do aluno é %s, ele tem %d anos e sua média é %f.' %(nome_aluno, idade_aluno, media_aluno))

print('Nome do aluno é %s, ele tem %d anos e sua média é %.2f.' %(nome_aluno, idade_aluno, media_aluno))

x = True
print("Valor de x: %s" % str(x))

nome_aluno = 'Fabricio Daniel'

print('Nome do aluno: {}'.format(nome_aluno))

nome_aluno = 'Fabricio Daniel'
idade_aluno = 15
media_aluno = 8.45

print('Nome do aluno é {}, ele tem {} anos e sua média é {}.' .format(nome_aluno, idade_aluno, media_aluno))

print("Estudar é um esforço constante,\nÉ como cultivar uma planta,\nPrecisamos de dedicação e paciência,\nPara ver o fruto amadurecer.")